name: CI/CD Docker

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/nestjs
  VERSION: ${{ github.sha }}
  NAME: nestjs

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          context: .
          build-args: |
            "DB_HOST=${{ secrets.DB_HOST }}"
            "DB_PORT=${{ secrets.DB_PORT }}"
            "DB_USERNAME=${{ secrets.DB_USERNAME }}"
            "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
            "DB_DATABASE=${{ secrets.DB_DATABASE }}"
            "JWT_SECRET=${{ secrets.JWT_SECRET }}"
            "HASH_ROUND=${{ secrets.HASH_ROUND }}"
            "KAKAO_JAVASCRIPT_KEY=${{ secrets.KAKAO_JAVASCRIPT_KEY }}"
            "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}"
            "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
            "GOOGLE_PASSWORD=${{ secrets.GOOGLE_PASSWORD }}"

  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker run
        run: |
          docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }} && docker rmi ${{ env.DOCKER_IMAGE }}:latest
          docker run --add-host=host.docker.internal:host-gateway -d -p 4000:4000 --name ${{ env.NAME }} --restart always ${{ env.DOCKER_IMAGE }}:latest
